---
driver:
  name: vagrant
  customize:
    memory: 9000
    cpuexecutioncap: 90
    cpus: 1
    natdnshostresolver1: "on"
    natdnsproxy1: "on"
    nictype1: "virtio"
  network:
  - ["forwarded_port", {guest: 8080, host: 18080}]
  - ["forwarded_port", {guest: 8181, host: 18181}]
  - ["forwarded_port", {guest: 4848, host: 14848}]
  - ["forwarded_port", {guest: 50070, host: 40070}]
  - ["forwarded_port", {guest: 50075, host: 41075}]

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
#  - name: centos-6.5

suites:
  - name: default

suites:
  - name: default
    run_list:
      - recipe[kagent::install]
      - recipe[dela::install]
      - recipe[dela::default]
    attributes:
         jdk_version: "7"
