---
driver:
  name: vagrant
  customize:
    memory: 9000
    cpuexecutioncap: 90
    cpus: 1
    natdnshostresolver1: "on"
    natdnsproxy1: "on"
    nictype1: "virtio"
  network:
  - ["forwarded_port", {guest: 18180, host: 18180}]
  - ["forwarded_port", {guest: 18181, host: 18181}]
  - ["forwarded_port", {guest: 30000, host: 30000, protocol: "udp"}]
  - ["forwarded_port", {guest: 42001, host: 42001, protocol: "udp"}]
  - ["forwarded_port", {guest: 41001, host: 41001, protocol: "udp"}]

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
#  - name: centos-7.0

suites:
  - name: default

suites:
  - name: default
    run_list:
      - recipe[kagent::install]
      - recipe[dela::install]
      - recipe[dela::default]
    attributes:
         jdk_version: "7"
